import 'package:auto_size_text/auto_size_text.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:shoppingmegamart/size.dart';

class NavigationDrawerPanel extends StatefulWidget {
  const NavigationDrawerPanel({Key? key, required this.data}) : super(key: key);
  final Map<String, dynamic> data;

  @override
  State<NavigationDrawerPanel> createState() => _NavigationDrawerPanelState();
}

class _NavigationDrawerPanelState extends State<NavigationDrawerPanel> {
  // NewApisProvider _provider = NewApisProvider();
  late Animation<double> _widthAnimation;
  late AnimationController _controller;

  @override
  void initState() {
    // setState(() {
    //   customerId = ConstantsVar.prefs.getString('userId');
    // });
    // _provider = Provider.of<NewApisProvider>(context, listen: false);
    //
    // _provider.getCategoryList(
    //     customerId: ConstantsVar.prefs.getString('guestCustomerID')!,
    //     needToRefresh: true,
    //     context: context);
    // TODO: implement initState
    super.initState();
  }

  String? customerId;

  @override
  Widget build(BuildContext context) {
    return Drawer(
      width: w * .85,
      backgroundColor: const Color(0xFFF7F7F7), // light gray background
      child: DefaultTabController(
        length: 2,
        child: Column(
          children: [
            // Custom Tab Bar
            Container(
              height: 110,
              color: Colors.white,
              child: TabBar(
                indicator: BoxDecoration(
                  color: Colors.grey[200], // solid light gray for selected tab
                ),
                indicatorColor: Colors.transparent,
                indicatorPadding:
                    EdgeInsets.only(bottom: 20, left: 0, right: 15),
                indicatorSize: TabBarIndicatorSize.tab,
                labelColor: Colors.black, // selected tab text color
                unselectedLabelColor:
                    Colors.blue[800], // unselected tab text color
                labelStyle: const TextStyle(
                    fontWeight: FontWeight.normal, fontSize: 17),
                tabs: const [
                  Tab(child: Text('Menu')),
                  Tab(child: Text('Account')),
                ],
              ),
            ),
            Container(
              height: 1,
              color: Color(0xFFE0E0E0), // light gray divider
            ),
            // Tab Views
            Expanded(
              child: TabBarView(
                children: [
                  // Menu Tab
                  ListView(
                    children: [
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      _buildExpansionTile('GRILLS & OUTDOOR COOKING'),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      _buildExpansionTile('BRANDS'),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      _buildExpansionTile('SHOP BY GRILL SIZE'),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      _buildExpansionTile('BBQ ACCESSORIES'),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      _buildExpansionTile('OUTDOOR KITCHENS'),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      _buildExpansionTile('COOKING'),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      _buildExpansionTile('OUTDOOR FURNITURE'),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      _buildExpansionTile('HEATING & MORE'),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      _buildExpansionTile('REFRIGERATORS'),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      _buildExpansionTile('CATEGORY'),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      _buildExpansionTile('LAUNDRY'),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      _buildExpansionTile('BIG GREEN EGG'),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                    ],
                  ),
                  // Account Tab
                  ListView(
                    children: [
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      const ListTile(
                        title: Text('Default welcome msg!',
                            style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: Colors.black,
                                fontSize: 18)),
                        tileColor: Colors.transparent,
                        contentPadding: EdgeInsets.symmetric(horizontal: 17),
                        dense: true,
                      ),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      const ListTile(
                        title: Text('Sign In',
                            style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: Colors.black,
                                fontSize: 18)),
                        tileColor: Colors.transparent,
                        contentPadding: EdgeInsets.symmetric(horizontal: 17),
                        dense: true,
                      ),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                      const ListTile(
                        title: Text('Create an Account',
                            style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: Colors.black,
                                fontSize: 18)),
                        tileColor: Colors.transparent,
                        contentPadding: EdgeInsets.symmetric(horizontal: 17),
                        dense: true,
                      ),
                      Container(height: 1, color: Color(0xFFE0E0E0)),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildExpansionTile(String title) {
    if (title == 'GRILLS & OUTDOOR COOKING') {
      return ExpansionTile(
        tilePadding: EdgeInsets.zero,
        childrenPadding: EdgeInsets.zero,
        title: Text(
          title,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 18,
            color: Colors.black87,
          ),
        ),
        children: [
          _drawerSubItem1('All Grills & Outdoor Cooking'),
          _drawerHeader('Outdoor Pizza Ovens'),
          _drawerSubItem('Wood Fired Pizza Ovens'),
          _drawerSubItem('Freestanding Pizza Ovens'),
          _drawerSubItem('Countertop Pizza Ovens'),
          _drawerSubItem('Gas Pizza Ovens'),
          _drawerHeader('Gas Grills'),
          _drawerSubItem('Propane Grills'),
          _drawerSubItem('Natural Gas Grills'),
          _drawerSubItem('Freestanding Gas Grills'),
          _drawerSubItem('Portable Gas Grills'),
          _drawerHeader('Charcoal Grills'),
          _drawerSubItem('Freestanding Charcoal Grills'),
          _drawerSubItem('Kettle Grills'),
          _drawerSubItem('Portable Charcoal Grills'),
          _drawerHeader('Flat Top Griddles'),
          _drawerSubItem('Griddle Grills'),
          _drawerSubItem('Portable Griddles'),
          _drawerHeader('Pellet Grills'),
          _drawerSubItem('Freestanding Pellet Grills'),
          _drawerSubItem('Portable Pellet Grills'),
          _drawerSubItem('WiFi Pellet Grills'),
          _drawerHeader('Electric Grills'),
          _drawerSubItem('Freestanding Electric Grills'),
          _drawerSubItem('Portable Electric Grills'),
          _drawerHeader('Kamado Grills'),
          _drawerSubItem('Freestanding Kamado Grills'),
          _drawerSubItem('Portable Kamado Grills'),
          _drawerHeader('Beyond the Backyard'),
          _drawerSubItem('Portable Grills'),
          _drawerSubItem('Camping Grills'),
          _drawerHeader('Santa Maria Gaucho Grills'),
          _drawerHeader('BBQ Smokers'),
          _drawerSubItem('Pellet Smokers'),
          _drawerSubItem('Offset Smokers'),
          _drawerSubItem('Vertical Smokers'),
          _drawerSubItem('Wood Smokers'),
          _drawerSubItem('Electric Smokers'),
          _drawerSubItem('Charcoal Smokers'),
          _drawerSubItem('Propane Smokers'),
          _drawerHeader('Outdoor Fryers & Stoves'),
          _drawerSubItem('Outdoor Fryers'),
          _drawerSubItem('Propane Burners & Stoves'),
          _drawerSubItem('Stock Pots & Baskets'),
        ],
      );
    }
    if (title == 'BRANDS') {
      return ExpansionTile(
        tilePadding: EdgeInsets.zero,
        childrenPadding: EdgeInsets.zero,
        title: Text(
          title,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 18,
            color: Colors.black87,
          ),
        ),
        children: [
          _drawerSubItem1('All Brands'),
          _drawerSubItem1('Alfa Pizza'),
          _drawerSubItem1('Alfa'),
          _drawerSubItem1('Alfresco'),
          _drawerSubItem1('American Fireglass'),
          _drawerSubItem1('American Fyre'),
          _drawerSubItem1('American Outdoor Grill'),
          _drawerSubItem1('American Outdoor Grills'),
          _drawerSubItem1('Artisan'),
          _drawerSubItem1('Blaze'),
          _drawerSubItem1('Bromic Heating'),
          _drawerSubItem1('Bromic'),
          _drawerSubItem1('Chicago'),
          _drawerSubItem1('Coyote Grills'),
          _drawerSubItem1('Coyote Outdoor Living'),
          _drawerSubItem1('Coyote'),
          _drawerSubItem1('Crossfire'),
          _drawerSubItem1('Cyclone Pneumatic'),
          _drawerSubItem1('DCS'),
          _drawerSubItem1('Delta Heat'),
          _drawerSubItem1('Fire Magic'),
          _drawerSubItem1('Aervoe'),
          _drawerSubItem1('Air King'),
          _drawerSubItem1('Victory'),
          _drawerSubItem1('Weber'),
          _drawerSubItem1('AOG'),
          _drawerSubItem1('Napoleon'),
          _drawerSubItem1('BBQ Authority'),
          _drawerSubItem1('BBQ Direct'),
          _drawerSubItem1('BBQ Dragon'),
          _drawerSubItem1('Tagwood BBQ'),
          _drawerSubItem1('Tagwood'),
          _drawerSubItem1('Alfresco Grills'),
          _drawerSubItem1('Alfa Pizza Ovens'),
          _drawerSubItem1('Weber Grills'),
          _drawerSubItem1('Pitts & Spitts'),
          _drawerSubItem1('Texas Longhorn BBQ Pits'),
          _drawerSubItem1('Evo Grills'),
          _drawerSubItem1('Evo'),
          _drawerSubItem1('Galindos TX BBQ Rubs'),
          _drawerSubItem1('Al Frugoni'),
          _drawerSubItem1('Huntington Brass'),
          _drawerSubItem1('Satco'),
          _drawerSubItem1('Dimplex'),
          _drawerSubItem1('Hestan'),
          _drawerSubItem1('Infratech'),
          _drawerSubItem1('Memphis Grills'),
          _drawerSubItem1('Memphis'),
          _drawerSubItem1('Mont Alpi'),
          _drawerSubItem1('PGS'),
          _drawerSubItem1('AEI'),
          _drawerSubItem1('Sunpak'),
          _drawerSubItem1('The Outdoor GreatRoom Company'),
          _drawerSubItem1('Stonefire'),
          _drawerSubItem1('The Outdoor Great room'),
          _drawerSubItem1('Cove'),
          _drawerSubItem1('Outdoor GreatRoom'),
          _drawerSubItem1('Uptown'),
          _drawerSubItem1('Providence'),
          _drawerSubItem1('Key Largo'),
          _drawerSubItem1('Cedar Ridge'),
          _drawerSubItem1('Twin Eagles'),
          _drawerSubItem1('Sunglo'),
          _drawerSubItem1('Lynx Pro'),
          _drawerSubItem1('Hinkley Lighting'),
          _drawerSubItem1('Everdure'),
          _drawerSubItem1('Magma Grills'),
          _drawerSubItem1('Flammkraft'),
          _drawerSubItem1('American Made Grills'),
          _drawerSubItem1('Broil King'),
          _drawerSubItem1('TEC Grills'),
          _drawerSubItem1('Halo'),
          _drawerSubItem1('Bull Grills'),
          _drawerSubItem1('Amg'),
          _drawerSubItem1('RCS'),
          _drawerSubItem1('Saber Grills'),
          _drawerSubItem1('Traeger'),
          _drawerSubItem1('Phoenix Grills'),
          _drawerSubItem1('Lynx'),
          _drawerSubItem1('TYTUS'),
          _drawerSubItem1('Lynx Grills'),
          _drawerSubItem1('Camp Chef'),
          _drawerSubItem1('Pit Boss'),
          _drawerSubItem1('Solaire'),
          _drawerSubItem1('Vintage'),
          _drawerSubItem1('Crown Verity'),
          _drawerSubItem1('Louisiana Grills'),
          _drawerSubItem1('Le Griddle'),
          _drawerSubItem1('Aspire'),
          _drawerSubItem1('Broilmaster'),
          _drawerSubItem1('Lion Premium Grills'),
          _drawerSubItem1('Sunstone Grills'),
          _drawerSubItem1('TEC'),
          _drawerSubItem1('Backyard Hibachi'),
          _drawerSubItem1('Officine Gullo'),
          _drawerSubItem1('Chicago Brick Oven'),
          _drawerSubItem1('Bull'),
          _drawerSubItem1('Turbo Grills'),
          _drawerSubItem1('ProFire'),
          _drawerSubItem1('Hancock Grills'),
          _drawerSubItem1('American Renaissance Grill'),
          _drawerSubItem1('Renaissance'),
          _drawerSubItem1('Wildfire Outdoor Living'),
          _drawerSubItem1('Perlick'),
          _drawerSubItem1('Traeger Pellet Grills'),
          _drawerSubItem1('Recteq'),
          _drawerSubItem1('Country Smokers'),
          _drawerSubItem1('Green Mountain Grills'),
          _drawerSubItem1('Kamado Joe'),
          _drawerSubItem1('Primo Ceramic Grills'),
          _drawerSubItem1('Primo Grills'),
          _drawerSubItem1('Lifesmart'),
          _drawerSubItem1('Rocket Outdoors'),
          _drawerSubItem1('BergHOFF'),
          _drawerSubItem1('Cuisinart'),
          _drawerSubItem1('Halo Products Group'),
          _drawerSubItem1('Schwank Outdoor Products'),
          _drawerSubItem1('Ooni'),
          _drawerSubItem1('Thor Kitchen'),
          _drawerSubItem1('Masterbuilt'),
          _drawerSubItem1('Meco'),
          _drawerSubItem1('ProQ'),
          _drawerSubItem1('Panacea Products'),
          _drawerSubItem1('Portable Kitchens'),
          _drawerSubItem1('Ultimate Patio'),
          _drawerSubItem1('Barebones Living'),
          _drawerSubItem1('Gather Grills'),
          _drawerSubItem1('PK Grills'),
          _drawerSubItem1('Bull Outdoor Products'),
          _drawerSubItem1('Burch Barrel'),
          _drawerSubItem1('Hasty-Bake'),
          _drawerSubItem1('Fire & Flavor'),
          _drawerSubItem1('Nuke'),
          _drawerSubItem1('Ninja'),
          _drawerSubItem1('Electri-Chef'),
          _drawerSubItem1('Kenyon'),
          _drawerSubItem1('Cookshack'),
          _drawerSubItem1('Smokin Tex'),
          _drawerSubItem1('Old Country BBQ Pits'),
          _drawerSubItem1('Keveir'),
          _drawerSubItem1('Backwoods Smoker'),
          _drawerSubItem1('Gateway Drum Smokers'),
          _drawerSubItem1('The Good One'),
          _drawerSubItem1('Good-One Manufacturing'),
          _drawerSubItem1('R & V Works'),
          _drawerSubItem1('Cru Ovens'),
          _drawerSubItem1('Bella Outdoor Living'),
          _drawerSubItem1('Tuscan Chef'),
          _drawerSubItem1('Solo Stove'),
          _drawerSubItem1('Brava'),
          _drawerSubItem1('Bayou Classic'),
          _drawerSubItem1('Hurricane Products'),
          _drawerSubItem1('BBQGuys Signature'),
          _drawerSubItem1('Outset'),
          _drawerSubItem1('Little Griddle'),
          _drawerSubItem1('Primo'),
          _drawerSubItem1('GrillPro'),
          _drawerSubItem1('Demeyere'),
          _drawerSubItem1('Rocky Mountain Cookware'),
          _drawerSubItem1('FornoVenezia'),
          _drawerSubItem1('WPPO'),
          _drawerSubItem1('The Outdoor Plus'),
          _drawerSubItem1('Aspire by Hestan'),
          _drawerSubItem1('Maverick'),
          _drawerSubItem1('Halo Products'),
          _drawerSubItem1('U-Line'),
          _drawerSubItem1('Zephyr'),
          _drawerSubItem1('Dragon Fire'),
          _drawerSubItem1('Fire Magic Grills'),
          _drawerSubItem1('Lion'),
          _drawerSubItem1('Empire'),
          _drawerSubItem1('Ohio Flame'),
          _drawerSubItem1('Extreme Fire'),
          _drawerSubItem1('Alcott'),
          _drawerSubItem1('American Fyre Designs'),
          _drawerSubItem1('Fire Pit Art'),
          _drawerSubItem1('Patio Comfort'),
          _drawerSubItem1('Bronson'),
          _drawerSubItem1('BROOKS'),
          _drawerSubItem1('Peterson Real Fyre'),
          _drawerSubItem1('Real Fyre'),
          _drawerSubItem1('Summit'),
          _drawerSubItem1('Summit Appliances'),
          _drawerSubItem1('Marvel'),
          _drawerSubItem1('Trade-Wind'),
          _drawerSubItem1('Darien'),
          _drawerSubItem1('Kenwood'),
          _drawerSubItem1('Naples'),
          _drawerSubItem1('Summerset'),
          _drawerSubItem1('Marvel Refrigeration'),
          _drawerSubItem1('Samsung'),
          _drawerSubItem1('Firegear'),
          _drawerSubItem1('Amantii'),
          _drawerSubItem1('Napoleon Fireplaces'),
          _drawerSubItem1('Havenwood'),
          _drawerSubItem1('RADtec'),
          _drawerSubItem1('Ledge Lounger'),
          _drawerSubItem1('PCM'),
          _drawerSubItem1('Elementi'),
          _drawerSubItem1('Monte Carlo'),
          _drawerSubItem1('Summit Appliance'),
          _drawerSubItem1('Franklin Offset Smoker'),
          _drawerSubItem1('Jealous Devil'),
          _drawerSubItem1('Alfa Pizza Oven'),
          _drawerSubItem1('Blackstone Products'),
          _drawerSubItem1('Blackstone'),
          _drawerSubItem1('Summerset Grills'),
          _drawerSubItem1('Empava'),
          _drawerSubItem1('KoKoMo Grills'),
          _drawerSubItem1('Char-Broil'),
          _drawerSubItem1('La Piazza'),
          _drawerSubItem1('Clementi'),
          _drawerSubItem1('Pinnacolo'),
          _drawerSubItem1('Franklin Offset'),
          _drawerSubItem1('Workhorse Pits'),
          _drawerSubItem1('Yoder Smokers'),
          _drawerSubItem1('TrueFlame'),
          _drawerSubItem1('True Refrigeration'),
          _drawerSubItem1('Hoshizaki'),
          _drawerSubItem1('Slick Rock Concrete'),
          _drawerSubItem1('Zio Ciro'),
          _drawerSubItem1('Lynx Sedona'),
          _drawerSubItem1('Jentek'),
          _drawerSubItem1('YS EL'),
          _drawerSubItem1('Gozney'),
          _drawerSubItem1('Shun'),
          _drawerSubItem1('Big Green Egg'),
          _drawerSubItem1('Fireboard'),
          _drawerSubItem1('Hardcore Carnivore'),
          _drawerSubItem1('Maverick Industries'),
          _drawerSubItem1('Epicurean'),
          _drawerSubItem1('B.B. Prime'),
          _drawerSubItem1('Mercer Culinary'),
          _drawerSubItem1('Black Disposable'),
          _drawerSubItem1('White Liner'),
          _drawerSubItem1('Three Little Pigs'),
          _drawerSubItem1('Dan-Os Seasoning'),
          _drawerSubItem1('Buck Grill'),
          _drawerSubItem1('Rinkmo'),
          _drawerSubItem1('Goldens Cast Iron'),
          _drawerSubItem1('HPC'),
          _drawerSubItem1('Sealoc'),
          _drawerSubItem1('Prism Hardscapes'),
          _drawerSubItem1('Modeno'),
          _drawerSubItem1('Kingsman'),
          _drawerSubItem1('Elementi Plus'),
          _drawerSubItem1('Buck Stove'),
          _drawerSubItem1('Real Flame'),
          _drawerSubItem1('American Specialty Glass'),
          _drawerSubItem1('Superior Fireplace Products'),
          _drawerSubItem1('Breckwell'),
          _drawerSubItem1('Majestic'),
          _drawerSubItem1('Monessen'),
          _drawerSubItem1('Osburn'),
          _drawerSubItem1('Vermont Stoves'),
          _drawerSubItem1('DuraVent'),
          _drawerSubItem1('Comfortbilt'),
          _drawerSubItem1('Ventis'),
          _drawerSubItem1('Drolet'),
          _drawerSubItem1('Ashley Hearth Products'),
          _drawerSubItem1('Timberwolf'),
          _drawerSubItem1('Diamond Hearths'),
          _drawerSubItem1('AllFuel HST'),
          _drawerSubItem1('Grand Canyon Gas Logs'),
          _drawerSubItem1('Lexington Hearth'),
          _drawerSubItem1('Phoenix Cast Products'),
          _drawerSubItem1('Schwank'),
          _drawerSubItem1('Modine'),
          _drawerSubItem1('Sterling'),
          _drawerSubItem1('Fuego'),
          _drawerSubItem1('Moss Grills'),
          _drawerSubItem1('Authentic Pizza Ovens'),
          _drawerSubItem1('Haven Outdoor'),
          _drawerSubItem1('Kingsbottle'),
          _drawerSubItem1('AzureRefrigeration'),
          _drawerSubItem1('Cal Flame'),
          _drawerSubItem1('KitchenAid'),
          _drawerSubItem1('KitchenAid WHIRLPOOL Maytag'),
          _drawerSubItem1('General Electric'),
          _drawerSubItem1('GE Profile GE APPLIANCES Monogram CAFE'),
          _drawerSubItem1('GE Appliances'),
          _drawerSubItem1('LG'),
          _drawerSubItem1('LG LG Studio'),
          _drawerSubItem1('Frigidaire'),
          _drawerSubItem1('FRIGIDAIRE Electrolux Frigidaire Gallery'),
          _drawerSubItem1('Frigidaire Professional'),
          _drawerSubItem1('JennAir'),
          _drawerSubItem1('JennAir WHIRLPOOL'),
          _drawerSubItem1('FRIGIDAIRE Frigidaire Professional'),
          _drawerSubItem1('GE APPLIANCES GE Profile'),
          _drawerSubItem1('Viking'),
          _drawerSubItem1('Verona'),
          _drawerSubItem1('Electrolux'),
          _drawerSubItem1('CA GE'),
          _drawerSubItem1('Fisher Paykel'),
          _drawerSubItem1('FISHER and PAYKEL'),
          _drawerSubItem1('FiveStar'),
          _drawerSubItem1('Fulgor'),
          _drawerSubItem1('Whirlpool'),
          _drawerSubItem1('Maytag'),
          _drawerSubItem1('Miele'),
          _drawerSubItem1('Dacor'),
          _drawerSubItem1('DACOR SAMSUNG'),
          _drawerSubItem1('NXR'),
          _drawerSubItem1('Capital'),
          _drawerSubItem1('Forza'),
          _drawerSubItem1('American Range'),
          _drawerSubItem1('Vintec'),
          _drawerSubItem1('Elica'),
          _drawerSubItem1('Liebherr'),
          _drawerSubItem1('Monogram'),
          _drawerSubItem1('Monogram GE Profile GE APPLIANCES CAFE'),
          _drawerSubItem1('Frigidaire Gallery'),
          _drawerSubItem1('SIGNATURE KITCHEN SUITE'),
          _drawerSubItem1('Thermador'),
          _drawerSubItem1('Gaggenau'),
          _drawerSubItem1('CAFE GE Profile GE APPLIANCES Monogram'),
          _drawerSubItem1('Cafe'),
          _drawerSubItem1('Beko'),
          _drawerSubItem1('Bertazzoni'),
          _drawerSubItem1('Haier'),
          _drawerSubItem1('Hotpoint'),
          _drawerSubItem1('SUB ZERO'),
          _drawerSubItem1('ZLINE KITCHEN AND BATH'),
          _drawerSubItem1('Avanti'),
          _drawerSubItem1('Forno'),
          _drawerSubItem1('BlueStar'),
          _drawerSubItem1('SMEG'),
          _drawerSubItem1('Amana'),
          _drawerSubItem1('AZURE HOME PRODUCTS'),
          _drawerSubItem1('Azure'),
          _drawerSubItem1('LG Studio'),
          _drawerSubItem1('Bosch'),
          _drawerSubItem1('GE Profile'),
          _drawerSubItem1('Speed Queen'),
          _drawerSubItem1('PROFILE'),
          _drawerSubItem1('LG Signature'),
          _drawerSubItem1('Asko'),
          _drawerSubItem1('Faber'),
          _drawerSubItem1('BEST'),
          _drawerSubItem1('BROAN'),
          _drawerSubItem1('Danby'),
          _drawerSubItem1('Galanz'),
          _drawerSubItem1('Vitara'),
          _drawerSubItem1('Scotsman'),
          _drawerSubItem1('Maxx Ice'),
          _drawerSubItem1('Premium Levella'),
          _drawerSubItem1('Sapphire'),
          _drawerSubItem1('WOLF'),
          _drawerSubItem1('PREMIER'),
          _drawerSubItem1('Foster'),
          _drawerSubItem1('BROWN COOKING'),
          _drawerSubItem1('Sharp'),
          _drawerSubItem1('AGA'),
          _drawerSubItem1('Fulgor Milano'),
          _drawerSubItem1('Sierra Flame'),
          _drawerSubItem1('Superior'),
          _drawerSubItem1('Electrolux Kitchen'),
          _drawerSubItem1('Balsam'),
          _drawerSubItem1('Denali'),
          _drawerSubItem1('Edison'),
          _drawerSubItem1('Flare'),
          _drawerSubItem1('Grand Canyon'),
          _drawerSubItem1('IronStrike'),
          _drawerSubItem1('Kinney'),
          _drawerSubItem1('Montigo'),
          _drawerSubItem1('Regency'),
          _drawerSubItem1('Sierra Square'),
          _drawerSubItem1('ADMIRAL'),
          _drawerSubItem1('Breda'),
        ],
      );
    }
    if (title == 'SHOP BY GRILL SIZE') {
      return ExpansionTile(
        tilePadding: EdgeInsets.zero,
        childrenPadding: EdgeInsets.zero,
        title: Text(
          title,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 18,
            color: Colors.black87,
          ),
        ),
        children: [
          _drawerSubItem('All Shop By Grill Size'),
          _drawerSubItem('Large Grills'),
          _drawerSubItem('Medium Grills'),
          _drawerSubItem('Small Grills'),
          _drawerSubItem('Large Size Grills'),
          _drawerSubItem('Medium Size Grills'),
          _drawerSubItem('49+ Inches'),
          _drawerSubItem('Small Size Grills'),
          _drawerSubItem('x-Large Size Grill'),
          _drawerSubItem('X-Large Grills'),
        ],
      );
    }
    if (title == 'BBQ ACCESSORIES') {
      return ExpansionTile(
        tilePadding: EdgeInsets.zero,
        childrenPadding: EdgeInsets.zero,
        title: Text(
          title,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 18,
            color: Colors.black87,
          ),
        ),
        children: [
          _drawerSubItem1('All BBQ Accessories'),
          _drawerHeader('Grill Replacement Parts'),
          _drawerSubItem('Gas Conversion Kits'),
          _drawerSubItem('Grill Burners'),
          _drawerSubItem('Flame Tamers'),
          _drawerSubItem('Grilling Grates'),
          _drawerSubItem('Gas Hoses & Regulators'),
          _drawerSubItem('Grill Ignitors'),
          _drawerSubItem('Grill Drip Pans'),
          _drawerHeader('Grill Covers'),
          _drawerHeader('Grill Cookware'),
          _drawerSubItem('Grill Racks & Roasters'),
          _drawerSubItem('BBQ Griddles'),
          _drawerSubItem('Grill Baskets & Toppers'),
          _drawerSubItem('Cast Iron Cookware'),
          _drawerHeader('Grill Attachments'),
          _drawerSubItem('Grill Rotisseries'),
          _drawerSubItem('Smoker Boxes'),
          _drawerSubItem('Temperature Controllers'),
          _drawerSubItem('Grill Lights'),
          _drawerHeader('Grilling Gifts'),
          _drawerSubItem('BBQ Gifts Under \$100'),
          _drawerHeader('Pizza Oven Accessories'),
          _drawerHeader('Kamado Grill Accessories'),
          _drawerHeader('Grilling Tools & Utensils'),
          _drawerSubItem('Grill Brushes'),
          _drawerSubItem('Grill Cleaning Tools'),
          _drawerSubItem('Grilling Thermometers'),
          _drawerSubItem('Grilling Tool Sets'),
          _drawerHeader('Charcoal'),
          _drawerHeader('Food Prep & Serving'),
          _drawerSubItem('BBQ Rubs & Sauces'),
          _drawerSubItem('Grilling Gloves & Aprons'),
          _drawerSubItem('Meat Injectors'),
          _drawerHeader('BBQ Knives & Cutlery'),
        ],
      );
    }
    if (title == 'OUTDOOR KITCHENS') {
      return ExpansionTile(
        tilePadding: EdgeInsets.zero,
        childrenPadding: EdgeInsets.zero,
        title: Text(
          title,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 18,
            color: Colors.black87,
          ),
        ),
        children: [
          _drawerSubItem1('All Outdoor Kitchens'),
          _drawerHeader('Built-In Grills'),
          _drawerSubItem('Built-In Gas Grills'),
          _drawerSubItem('Built-In Smokers'),
          _drawerSubItem('Built-In Charcoal Grills'),
          _drawerSubItem('Built-In Gas Griddles'),
          _drawerSubItem('Built-In Pellet Grills'),
          _drawerSubItem('Built-In Electric Grills'),
          _drawerSubItem('Built-In Kamado Grills'),
          _drawerHeader('Side Burners'),
          _drawerSubItem('Power Burners'),
          _drawerSubItem('Single Side Burners'),
          _drawerSubItem('Double Side Burners'),
          _drawerSubItem('Infrared Searing Stations'),
          _drawerHeader('Built-In Pizza Ovens'),
          _drawerHeader('Outdoor Refrigerators'),
          _drawerSubItem('Outdoor Kegerators'),
          _drawerSubItem('Outdoor Ice Makers'),
          _drawerSubItem('Compact Refrigerators'),
          _drawerSubItem('Outdoor Wine Coolers'),
          _drawerSubItem('Outdoor Beverage Fridges'),
          _drawerSubItem('Outdoor Compact Freezers'),
          _drawerHeader('Sink Stations & Bar Centers'),
          _drawerSubItem('Outdoor Sinks'),
          _drawerSubItem('Wet Bars & Bar Centers'),
          _drawerSubItem('Ice Bin & Coolers'),
          _drawerSubItem('Outdoor Kitchen Faucets'),
          _drawerHeader('Outdoor Kitchen Cabinets'),
          _drawerSubItem('Outdoor Kitchen Doors'),
          _drawerSubItem('Outdoor Kitchen Drawers'),
          _drawerSubItem('Outdoor Kitchen Paper Towel Bins'),
          _drawerSubItem('Door & Drawer Combos'),
          _drawerSubItem('Outdoor Kitchen Propane Tank Bins'),
          _drawerSubItem('Roll Out & Pull Out Trash Bins'),
          _drawerSubItem('Outdoor Kitchen Enclosed Cabinets'),
          _drawerHeader('Warming Drawers'),
          _drawerHeader('BBQ Islands & Kits'),
          _drawerSubItem('Insulated Grill Jackets'),
          _drawerSubItem('Outdoor Kitchen Kits'),
          _drawerSubItem('Outdoor Kitchen Cabinetry Kits'),
          _drawerSubItem('Outdoor Kitchen Trim Kits'),
          _drawerSubItem('BBQ Island Frame Kits'),
          _drawerSubItem('Outdoor Kitchen Equipment Packages'),
          _drawerHeader('Outdoor Vent Hoods'),
          _drawerSubItem('BBQ Island Vent Panels'),
          _drawerSubItem('Grill & Range Hoods'),
          _drawerHeader('Outdoor Kitchen Learning Center'),
          _drawerSubItem('Outdoor Kitchen Cost'),
          _drawerSubItem('Outdoor Kitchen Ideas'),
        ],
      );
    }
    if (title == 'COOKING') {
      return ExpansionTile(
        tilePadding: EdgeInsets.zero,
        childrenPadding: EdgeInsets.zero,
        title: Text(
          title,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 18,
            color: Colors.black87,
          ),
        ),
        children: [
          _drawerSubItem1('All Cooking'),
          _drawerHeader('Wall Ovens'),
          _drawerSubItem('Warming Drawers'),
          _drawerSubItem('Single Wall Ovens'),
          _drawerSubItem('Double Wall Ovens'),
          _drawerSubItem('Steam Ovens'),
          _drawerSubItem('Speed Ovens'),
          _drawerSubItem('Microwave + Oven Combos'),
          _drawerHeader('Shop Luxury Ranges'),
          _drawerHeader('Stoves / Ranges'),
          _drawerSubItem('Gas Ranges'),
          _drawerSubItem('Electric Ranges'),
          _drawerSubItem('Induction Ranges'),
          _drawerSubItem('Dual Fuel Ranges'),
          _drawerHeader('Cooktops & Rangetops'),
          _drawerSubItem('Gas Cooktops'),
          _drawerSubItem('Induction Cooktops'),
          _drawerSubItem('Rangetops'),
          _drawerSubItem('Electric Cooktops'),
          _drawerHeader('Microwaves'),
          _drawerSubItem('Microwave Drawers'),
          _drawerSubItem('Over the Range Microwaves'),
          _drawerSubItem('Over the Counter Microwaves'),
          _drawerSubItem('Built In Microwaves'),
          _drawerSubItem('Countertop Microwaves'),
          _drawerHeader('Ventilation'),
          _drawerSubItem('Wall Mount Hoods'),
          _drawerSubItem('Hood Liners'),
          _drawerSubItem('Island Hoods'),
          _drawerSubItem('Under Cabinet Hoods'),
          _drawerSubItem('Downdraft Hoods'),
          _drawerHeader('Range Hoods'),
          _drawerHeader('Induction Cooking'),
          _drawerHeader('Smart Cooking Appliances'),
          _drawerHeader('Pizza Ovens'),
        ],
      );
    }
    if (title == 'OUTDOOR FURNITURE') {
      return ExpansionTile(
        tilePadding: EdgeInsets.zero,
        childrenPadding: EdgeInsets.zero,
        title: Text(
          title,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 18,
            color: Colors.black87,
          ),
        ),
        children: [
          _drawerSubItem1('All Outdoor Furniture'),
          _drawerHeader('Outdoor Dining Furniture'),
          _drawerSubItem('Outdoor Buffet & Serving Tables'),
          _drawerSubItem('Outdoor Dining Tables'),
          _drawerHeader('Fire Pit Sets'),
          _drawerSubItem('Fire Pit Dining Sets'),
          _drawerHeader('Outdoor Bar Furniture'),
          _drawerSubItem('Outdoor Bar Sets'),
          _drawerSubItem('Outdoor Bar Stools'),
          _drawerHeader('Pool Furniture'),
          _drawerHeader('Outdoor Chairs'),
          _drawerSubItem('Adirondack Chairs'),
          _drawerSubItem('Outdoor Lounge Chairs'),
          _drawerHeader('Outdoor Cushions'),
        ],
      );
    }
    if (title == 'HEATING & MORE') {
      return ExpansionTile(
        tilePadding: EdgeInsets.zero,
        childrenPadding: EdgeInsets.zero,
        title: Text(
          title,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 18,
            color: Colors.black87,
          ),
        ),
        children: [
          _drawerSubItem1('All Heating & More'),
          _drawerHeader('Patio Heaters'),
          _drawerSubItem('Electric Patio Heaters'),
          _drawerSubItem('Gas Patio Heaters'),
          _drawerSubItemCeiling('Freestanding Gas Patio Heaters'),
          _drawerSubItemCeiling('Ceiling & Wall Mounted Outdoor Gas Heaters'),
          _drawerSubItem('Commercial Patio Heaters'),
          _drawerSubItem('Patio Heater Accessories'),
          _drawerSubItemCeiling('Patio Heater Remotes & Control Systems'),
          _drawerHeader('Fire Pit Accessories'),
          _drawerSubItem('Fire Pit Wind Guards'),
          _drawerSubItem('Fire Glass'),
          _drawerSubItem('Fire Pit Covers'),
          _drawerSubItem('Log Racks'),
          _drawerSubItem('Fire Pit Controls & Parts'),
          _drawerSubItem('Fire Pit Lids'),
          _drawerSubItem('Fire Pit Propane Tank Covers'),
          _drawerHeader('Fireplaces'),
          _drawerSubItem1('Electric Fireplaces'),
          _drawerSubItem('Built-In Electric Fireplaces'),
          _drawerSubItem('Mantle Electric Fireplaces'),
          _drawerSubItem('Electric Fireplace Inserts'),
          _drawerSubItem('Freestanding Electric Fireplaces'),
          _drawerSubItem('Wall Mount Electric Fireplaces'),
          _drawerSubItem('Brick & Stone Fireplace Inserts'),
          _drawerSubItem('Electric Fireplace Inserts'),
          _drawerSubItem('Pellet Inserts'),
          _drawerSubItem('Wood Burning Fireplace Inserts'),
          _drawerSubItem('Gas Fireplace Inserts'),
          _drawerSubItem1('Heating Stoves'),
          _drawerSubItem('Cast Iron Stoves'),
          _drawerSubItem('Gas Stoves'),
          _drawerSubItem('Cooking And Heating Stoves'),
          _drawerSubItem('Wood Stoves'),
          _drawerSubItem('Pellet Stoves'),
          _drawerSubItem('Stove Pipe & Accessories'),
          _drawerSubItem('Hearth Pads'),
          _drawerSubItem1('Fireplace Accessories'),
          _drawerSubItem('Gas Logs'),
          _drawerSubItem('Fireplace Tools & Racks'),
          _drawerSubItem('Fire Glass'),
          _drawerSubItem('Fireplace Screens & Doors'),
          _drawerSubItem('Fireplace Mantels'),
          _drawerSubItem1('Outdoor Gas Fireplaces'),
          _drawerSubItem1('Built In Fireplaces'),
          _drawerSubItem('Built In Gas Fireplaces'),
          _drawerSubItem('Built In Wood Burning Fireplaces'),
          _drawerSubItem1('Natural Gas Outdoor Fireplaces'),
          _drawerSubItem1('Propane Outdoor Fireplaces'),
          _drawerSubItem1('Gas Log Sets & Accessories'),
          _drawerSubItem('Outdoor Gas Logs'),
          _drawerSubItem('Vented Gas Logs'),
          _drawerSubItem('Ventless Gas Logs'),
          _drawerSubItem('Gas Log Remotes & Controls'),
          _drawerSubItem1('Indoor Gas Fireplaces'),
          _drawerSubItem('Vented Gas Fireplaces'),
          _drawerSubItem('Vent Free Gas Fireplaces'),
          _drawerSubItem('Linear Gas Fireplaces'),
          _drawerSubItem('Freestanding Gas Fireplaces'),
          _drawerSubItem('See Thru and Multi-Side Gas Fireplaces'),
          _drawerHeader('Fireplace Builder Boxes'),
          _drawerHeader('Fire Pits'),
          _drawerSubItem('Fire Pit Tables'),
          _drawerSubItem('Smokeless Fire Pits'),
          _drawerSubItem('Wood Burning Fire Pits'),
          _drawerSubItem('Extreme Fire Pits'),
          _drawerSubItem('Gas Fire Pits'),
          _drawerHeader('Fire Bowls'),
          _drawerHeader('Outdoor Cooling'),
          _drawerSubItem('Outdoor Ceiling Fans'),
          _drawerHeader('DIY Fire Pit Kits'),
          _drawerHeader('Shop Fire Pits by Shape'),
          _drawerSubItem('Round Fire Pits'),
          _drawerSubItem('Square Fire Pits'),
          _drawerSubItem('Unique Fire Pit Burners'),
          _drawerSubItem('Rectangular Fire Pits'),
          _drawerSubItem('Linear Fire Pit Burners'),
          _drawerHeader('Outdoor Décor'),
          _drawerSubItem('Outdoor Pillows'),
          _drawerHeader('Outdoor TVs & Audio'),
          _drawerSubItem('Outdoor TVs'),
        ],
      );
    }
    if (title == 'REFRIGERATORS') {
      return ExpansionTile(
        tilePadding: EdgeInsets.zero,
        childrenPadding: EdgeInsets.zero,
        title: Text(
          title,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 18,
            color: Colors.black87,
          ),
        ),
        children: [
          _drawerSubItem1('All Refrigerators'),
          _drawerSubItem2('All Refrigerators'),
          _drawerSubItem2('Wine Cooler & Beverage Center'),
          _drawerSubItem2('Refrigerator & Freezer Drawers'),
          _drawerSubItem2('Freezer & Ice Makers'),
          _drawerSubItem2('Compact Refrigerators'),
          _drawerSubItem2('Side By Side Refrigerators'),
          _drawerSubItem2('Bottom Freezer Refrigerators'),
          _drawerSubItem2('Freezerless Refrigerators'),
          _drawerSubItem2('French Door Refrigerators'),
          _drawerSubItem2('Built-In French Door Refrigerator'),
          _drawerSubItem2('Built-In Full Refrigerator / Freezers'),
          _drawerSubItem2('Built-In Bottom Freezer Refrigerator'),
          _drawerSubItem2('Top Freezer Refrigerators'),
          _drawerSubItem2('Refrigerator Accessories'),
          _drawerSubItem2('Built-In Side-by-Side Refrigerator'),
        ],
      );
    }
    if (title == 'LAUNDRY') {
      return ExpansionTile(
        tilePadding: EdgeInsets.zero,
        childrenPadding: EdgeInsets.zero,
        title: Text(
          title,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 18,
            color: Colors.black87,
          ),
        ),
        children: [
          _drawerSubItem1('All Laundry'),
          _drawerSubItem2('All Laundry'),
          _drawerSubItem2('Washers'),
          _drawerSubItem2('Commercial Washers'),
          _drawerSubItem2('Dryers'),
          _drawerSubItem2('Commercial Dryers'),
          _drawerSubItem2('Stacked Washer Dryer Units'),
          _drawerSubItem2('Washer & Dryer Pedestals'),
          _drawerSubItem2('Washer & Dryer Sets'),
          _drawerSubItem2('Washer Dryer Combo Units'),
          _drawerSubItem2('Laundry Accessories'),
        ],
      );
    }
    if (title == 'BIG GREEN EGG') {
      return ExpansionTile(
        tilePadding: EdgeInsets.zero,
        childrenPadding: EdgeInsets.zero,
        title: Text(
          title,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 18,
            color: Colors.black87,
          ),
        ),
        children: [
          _drawerSubItem1('All Big Green Egg'),
          _drawerHeader('Big Green Egg'),
        ],
      );
    }
    return ExpansionTile(
      tilePadding: EdgeInsets.zero,
      childrenPadding: EdgeInsets.zero,
      title: Text(
        title,
        style: const TextStyle(
            fontWeight: FontWeight.bold, color: Colors.black87, fontSize: 18),
      ),
      children: const [], // No subcategories for now
    );
  }

  Widget _drawerMainText(String text) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 5, vertical: 10),
      child: Align(
        alignment: Alignment.centerLeft,
        child: Text(
          text,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 18,
            color: Colors.black87,
          ),
        ),
      ),
    );
  }

  Widget _drawerHeader(String text) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 5, vertical: 10),
      child: Align(
        alignment: Alignment.centerLeft,
        child: Text(
          text,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 16,
            color: Colors.black87,
          ),
        ),
      ),
    );
  }

  Widget _drawerSubItem1(String text) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 5, vertical: 10),
      child: Align(
        alignment: Alignment.centerLeft,
        child: Text(
          text,
          style: const TextStyle(
            fontSize: 17,
          ),
        ),
      ),
    );
  }

  Widget _drawerSubItem2(String text) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 5, vertical: 10),
      child: Align(
        alignment: Alignment.centerLeft,
        child: Text(
          text,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 16,
            // color: Colors.black87,
          ),
        ),
      ),
    );
  }

  Widget _drawerSubItemCeiling(String text) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 30, vertical: 10),
      child: Align(
        alignment: Alignment.centerLeft,
        child: Text(
          text,
          style: const TextStyle(
            fontSize: 17,
            // color: Colors.black87,
          ),
        ),
      ),
    );
  }

  Widget _drawerSubItem(String text) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
      child: Align(
        alignment: Alignment.centerLeft,
        child: Text(
          text,
          style: const TextStyle(
            fontWeight: FontWeight.normal,
            fontSize: 17,
            color: Colors.black87,
          ),
        ),
      ),
    );
  }
}

//in this screenshoot logic is when click on menu then bacground tab tranfer
// in account and when click on account then transfer on menu and in when tab bacground in menu then opens account section and when tab background in account then open menu section then create this logic if in menu in tab background is not shown then if we click menu then it should not be work. then same logic build
