// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCghL5nKLSkTwQQT1yU475SS7vhVpjdZnA',
    appId: '1:998485099147:android:33fb6ec6672e62b830ca8e',
    messagingSenderId: '998485099147',
    projectId: 'msp-project-215c5',
    storageBucket: 'msp-project-215c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN1Hrydtcn7BFsz7XDQC5h2futFLZi8W8',
    appId: '1:998485099147:ios:84ace253e2c46e8330ca8e',
    messagingSenderId: '998485099147',
    projectId: 'msp-project-215c5',
    storageBucket: 'msp-project-215c5.appspot.com',
    androidClientId: '998485099147-rdsnf84n5clptdvvddpie00hee6k9kcr.apps.googleusercontent.com',
    iosClientId: '998485099147-mqekp8rh459lb34b4j4b2pbjcf001egd.apps.googleusercontent.com',
    iosBundleId: 'com.example.mspEcommerece',
  );
}
